// Code generated by astool. DO NOT EDIT.

package streams

import (
	propertyid "github.com/poast-social/activity/streams/impl/jsonld/property_id"
	propertytype "github.com/poast-social/activity/streams/impl/jsonld/property_type"
	vocab "github.com/poast-social/activity/streams/vocab"
)

// NewJSONLDJSONLDTypeProperty creates a new JSONLDTypeProperty
func NewJSONLDTypeProperty() vocab.JSONLDTypeProperty {
	return propertytype.NewJSONLDTypeProperty()
}

// NewJSONLDJSONLDIdProperty creates a new JSONLDIdProperty
func NewJSONLDIdProperty() vocab.JSONLDIdProperty {
	return propertyid.NewJSONLDIdProperty()
}
